Update to allow use of backup exclusion file for omitting content from backups
GameServerManagers/LinuxGSM pull request #2312
Opened 2019-04-27 06:19 UTC by jimmyatSplunk

I've reworked the backup command to use a flat file that is used for file and folder exclusions in an attempt to allow admins to exclude files or folders from their backups. The idea being they can exclude game files that will be replaced by repairing the game server and it helps keep their backups smaller.

I've also added the necessary exclude file variable and a check for the "backupexclude.cfg" in the same fashion as "common.cfg" and "instance.cfg" so it should fold into current installations without issue.

2019-04-27 06:20 UTC, jimmyatSplunk commented
This request is essentially the same request as https://github.com/GameServerManagers/LinuxGSM/pull/1595#issue-137964814 but there are more changes in that that have nothing to do with implementing this improvement so it should be rejected and closed.

2019-04-27 06:21 UTC, Frisasky commented
please commit into develop branch as master branch are used for script release

2019-04-27 10:17 UTC, dgibbs64 commented
Looks great :). I will need to review this to make sure I fully understand how this all works and do testing. So please bear with me on this might take a little time to merge

2019-04-27 10:19 UTC, dgibbs64 commented
I think a backup re-factor is in order

2019-06-10 16:22 UTC, h3o66 commented on linuxgsm.sh
> +version="190422"
i guess this should not be in the commit, as the version is changed by release.

2020-12-30 12:26 UTC, h3o66 requested changes
Please rebase and resolve the conflicts

2021-01-27 20:51 UTC, closed without merging