Feature/openttd
GameServerManagers/LinuxGSM pull request #2908
Opened 2020-05-27 03:11 UTC by ttocszed00

# Description

Adds support for Open Transport Tycoon Deluxe.
the only thing that doesnt work is update. once they push a new update I can recompile the server.

Fixes #2454

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [X] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [X] This pull request links to an issue.
* [X] This pull request uses the `develop` branch as its base.
* [X] This pull request Subject follows the Conventional Commits standard.
* [X] This code follows the style guidelines of this project.
* [X] I have performed a self-review of my code.
* [X] I have checked that this code is commented where required.
* [X] I have provided a detailed with enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

2020-06-17 22:18 UTC, dgibbs64 commented
Ran into a few problems with this.

GLIBC requirements at 2.29 for some reason
No auto-update method

The standard install method is using a deb which fell over when I tried

Maybe a solution is to use the github releases to check version and compile from source?

2020-12-05 22:05 UTC, h3o66 requested changes
As well this needs to be rebased to the latest release

2020-12-05 22:05 UTC, h3o66 commented on .github/workflows/git-sync.yml
> -    branches:
this should not be in the PR

2020-12-05 22:05 UTC, h3o66 commented on lgsm/functions/core_functions.sh
> -modulesversion="v20.3.2"
Versions should not be increased.
Please us for this the `clear-functions` of the dev commands for the tests

2020-12-05 22:05 UTC, h3o66 commented on lgsm/functions/install_server_files.sh
> +		remote_fileurl="http://linuxgsm.download/UnrealTournament3/UT3-linux-server-2.1.tar.xz"; local_filedir="${tmpdir}"; local_filename="UT3-linux-server-2.1.tar.xz"; chmodx="nochmodx" run="norun"; forc
For whateven reason this is here

2020-12-05 22:05 UTC, h3o66 commented on linuxgsm.sh
> -version="v20.3.2"
Versions should not be increased, see other comment.

2020-12-05 22:05 UTC, h3o66 commented on tests/tests_fctrserver.sh
> +version="v20.3.3"
Versions should not be increased, see other comment.

2020-12-05 22:05 UTC, h3o66 commented on tests/tests_jc2server.sh
> +version="v20.3.3"
Versions should not be increased, see other comment.

2020-12-05 22:05 UTC, h3o66 commented on tests/tests_mcserver.sh
> +version="v20.3.3"
Versions should not be increased, see other comment.

2020-12-05 22:05 UTC, h3o66 commented on tests/tests_ts3server.sh
> +version="v20.3.3"
Versions should not be increased, see other comment.

2020-12-05 22:06 UTC, h3o66 commented
> Ran into a few problems with this.
> 
> GLIBC requirements at 2.29 for some reason
> No auto-update method
> 
> The standard install method is using a deb which fell over when I tried
> 
> Maybe a solution is to use the github releases to check version and compile from source?

This should be probably recompiled on a CentOS 7, as this has the lowest version dependency

2021-01-06 01:29 UTC, closed without merging