[WIP] feat(newserver): Colony Survival
GameServerManagers/LinuxGSM pull request #3075
Opened 2020-10-08 22:07 UTC by h3o66

# Description

Please include a summary of the change and which issues are fixed.

Fixes #[issue]

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [ ] New feature (change which adds functionality).
* [x] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [x] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [x] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

2020-10-08 22:11 UTC, dgibbs64 commented on lgsm/functions/info_messages.sh
> +        echo -e ""
using spaces instead of tabs

2020-11-22 19:27 UTC, dgibbs64 commented
I tested and Im getting this error

```
[2020-11-22_19-25-00][Warning]:Stopped due to missing options or serverlock fail
```

any ideas?

2020-12-29 16:52 UTC, h3o66 commented
New changes with the latest update 0.8.1 :
- Generate a random seed if none is provided via the JSON-config launch option
- Automatically fall back to loading a world if the world passed via JSON-config launch exists

With this no more fix is required from our side.

2020-12-29 17:03 UTC, h3o66 commented
The new changes look good to me, if someone else wants to test feel free to do so.

2020-12-29 17:22 UTC, dgibbs64 requested changes
Please get monitor working correctly. Requires a query port for port querying (if supported)
```
./colserver query-raw
```
command might be useful doe tou
```
lgsm@lgsm-ubuntu-2004:~/colserver$ ./colserver m
[  OK  ] Monitoring colserver: Checking session: OK
[ ERROR ] Monitoring colserver: Checking port: Unable to query, queryport is not setERROR
```

2020-12-29 18:05 UTC, h3o66 commented
> Please get monitor working correctly. Requires a query port for port querying (if supported)
> 
> ```
> ./colserver query-raw
> ```
> 
> command might be useful doe tou
> 
> ```
> lgsm@lgsm-ubuntu-2004:~/colserver$ ./colserver m
> [  OK  ] Monitoring colserver: Checking session: OK
> [ ERROR ] Monitoring colserver: Checking port: Unable to query, queryport is not setERROR
> ```

should be working now with the last commit.

2020-12-30 10:13 UTC, dgibbs64 approved these changes

2020-12-30 10:14 UTC, merged