feature/amxmodx hl1 classic
GameServerManagers/LinuxGSM pull request #3104
Opened 2020-11-18 15:03 UTC by tkrn

# Description
The initial Metamod was renamed to Metamod: Source for accurate in-code representation. Metamod by itself refers to the HL1/goldsrc engines. Metamod along with amxmodx (base) and game specific versions were added for supported goldsrc engines. It also modifies required files liblist.gam and plugin.ini for Metamod. The majority of the testing has been done against csserver but all the other varients such as dod, tfc, ns, and ts also ahear to the exact same logic. Added logic for dependencies (metamod, amxmodx) while installing. The only to do item *maybe* is to add dependency checks while removing/updating a mod. The likely hood of these mods being updated is slim given the age of the game/mods.

Fulfills request of feature (issue # 2256)

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [X] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [X] This pull request links to an issue.
* [X] This pull request uses the `develop` branch as its base.
* [X] This pull request Subject follows the Conventional Commits standard.
* [X] This code follows the style guidelines of this project.
* [X] I have performed a self-review of my code.
* [X] I have checked that this code is commented where required.
* [X] I have provided a detailed with enough description of this PR.
* [X] I have checked If documentation needs updating.

## Documentation

This will need to be updated after it is tested/merged - https://docs.linuxgsm.com/commands/mods#supported-mods-add-ons

2020-11-18 21:01 UTC, dgibbs64 requested changes
Skimming over the code it looks good. I would like a volunteer to test the code and leave a review

2020-11-18 21:01 UTC, dgibbs64 commented on lgsm/functions/mods_list.sh
> +=======
Remove this

2020-11-18 21:01 UTC, dgibbs64 commented on lgsm/functions/mods_list.sh
> +>>>>>>> first release of metamod/amxmodx for goldsrc/hl1 engines
remove this

2020-11-18 21:01 UTC, dgibbs64 commented on lgsm/functions/mods_list.sh
> +<<<<<<< HEAD
This is a merge compare

2020-11-19 14:24 UTC, tkrn commented
Removed the accidental merge compare in commit d1d0f81.

2020-11-19 21:47 UTC, dgibbs64 submitted a review, later dismissed
Ran a test and looks like it works 👍

2020-11-19 22:03 UTC, merged

2020-11-20 01:24 UTC, tkrn commented
See pull request for documentation update - https://github.com/GameServerManagers/LinuxGSM-Docs/pull/50