feature(core): add new functions for github releases
GameServerManagers/LinuxGSM pull request #3164
Opened 2021-01-08 23:01 UTC by h3o66

# Description

Add new functions for further refactors and usage for gameservers

## Type of change

* [ ] Bug fix (a change which fixes an issue).
* [x] New feature (change which adds functionality).
* [ ] New Server (new server added).
* [ ] Refactor (restructures existing code).
* [ ] Comment update (typo, spelling, explanation, examples, etc).

## Checklist

PR will not be merged until all steps are complete.

* [ ] This pull request links to an issue.
* [x] This pull request uses the `develop` branch as its base.
* [x] This pull request Subject follows the Conventional Commits standard.
* [x] This code follows the style guidelines of this project.
* [x] I have performed a self-review of my code.
* [x] I have checked that this code is commented where required.
* [x] I have provided a detailed with enough description of this PR.
* [ ] I have checked If documentation needs updating.

## Documentation

If documentation does need updating either update it by creating a PR (preferred) or request a documentation update.
* User docs: https://github.com/GameServerManagers/LinuxGSM-Docs
* Dev docs: https://github.com/GameServerManagers/LinuxGSM-Dev-Docs

**Thank you for your Pull Request!**

2021-01-09 11:13 UTC, h3o66 commented
Added a few more error checks to prevent a case where no version of file can be get from the api due network problems

2021-01-09 21:12 UTC, dgibbs64 submitted a review, later dismissed

2021-01-10 16:13 UTC, h3o66 commented
Made a few more litte changes as the new core_dl function was missung another proper error check, also rebased

2021-01-14 22:06 UTC, dgibbs64 requested changes
Most of the comments are minor "picky" changes do to do with spelling or LinuxGSM code standards. Looking good

2021-01-14 22:06 UTC, dgibbs64 commented on lgsm/functions/core_dl.sh
> +			# fetch file from the remote location from the exiting function to the ${tmpdir} for now
Should it be `existing` rather than `exiting`?

Also all comments should be treated like a normal sentence with Capital and full stop at the end.

2021-01-14 22:06 UTC, dgibbs64 commented on lgsm/functions/core_dl.sh
> +	local github_release_user="${1}"
Is this indent space or tab? it is not clear on GitHub? The standard should be a `tab`

2021-01-14 22:06 UTC, dgibbs64 commented on lgsm/functions/core_dl.sh
> +
remove CR

2021-01-14 22:49 UTC, h3o66 commented
Hopefully got all now, please review again

2021-01-17 22:32 UTC, dgibbs64 approved these changes

2021-01-17 22:33 UTC, merged